### ISSUE TITLE
Set the link to the URL for the repository

### ISSUE THREAD

**Issue by mbainter** [stopthessotax/sso-wall-of-shame#18]
Top right, the gear next to About, put the stopthesso.tax URL under website so it's easy for people to find.  

Also is probably a good idea to feature it prominently in the Readme.

**Comment by BowlesCR** [comment]
Might also be good to explain the fork somewhere.

**Comment by derekcwhite** [comment]
@mbainter added the details to About

Filed https://github.com/stopthessotax/sso-wall-of-shame/pull/22 to add info about the fork
