### ISSUE TITLE
Docker Percent Increase Incorrect

### ISSUE THREAD

**Issue by rlywtf** [stopthessotax/sso-wall-of-shame#51]
I'm unsure if the site just hasn't been deployed in a while or not but the listed % increase for Docker on the webpage shows 200% while the committed code shows 300%.

**RE:** This commit https://github.com/stopthessotax/sso-wall-of-shame/commit/7985bc0a9d84460331a30a6a686127878e7f7540

![image](https://user-images.githubusercontent.com/53841159/192875897-69ab19e0-8254-4be8-9d22-acf3023e5d3f.png)

**Comment by daallgeier** [comment]
This is an interesting change you detected here.  But i think i know where the confusion comes from.  
This commit is deploying to https://stopthesso.tax rather than https://sso.tax.  We initiated this fork to ensure that we can deploy updates faster than the original repo.

**Comment by doransmestad** [comment]
Double checked and it does look correctly to be 300% on https://stopthesso.tax so I'm going to close this issue out. 

![image](https://user-images.githubusercontent.com/8120019/234727837-febaa62b-344f-4cb7-8a3a-af12a2cc6e55.png)
