### ISSUE TITLE
DNS for stopthesso.tax returning a SERVFAIL

### ISSUE THREAD

**Issue by doransmestad** [stopthessotax/sso-wall-of-shame#7]
Hey @derekcwhite!   Thanks for setting up the organization, great idea.   I archived my fork and removed the CNAME file pointing at stopthesso.tax so I think we can update the DNS to point to GitHub pages here.  

Looks like my current attempts to resolve the domain are coming up as SERVFAIL:

```
$ dig @8.8.8.8 stopthesso.tax

; <<>> DiG 9.16.1-Ubuntu <<>> @8.8.8.8 stopthesso.tax
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 62181
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;stopthesso.tax.			IN	A

;; Query time: 47 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jul 28 01:16:47 EDT 2021
;; MSG SIZE  rcvd: 43
```

**Comment by derekcwhite** [comment]
Fixed! I wasn't able to use stopthesso.tax with github pages until you removed it from the previous repo.
